#!/usr/bin/env perl
#use strict;
#use warnings;

use Data::Dumper;
use Storable;
use LWP::UserAgent;
require LWP::Authen::OAuth;

$Storable::Eval = 1;

my $ua = retrieve('./fitbitagent');

my $response_format = 'json';
my $api_version = '1';
my $api_base_url = "https://api.fitbit.com";
my $info_get_url = "/$api_version/user/-/profile.$response_format";
my $activity_post_url = "/$api_version/user/-/activities.$response_format";

my $request = $ua->post( $api_base_url.$info_get_url);
die $request->as_string;
