#!/usr/bin/env perl
use strict;
use warnings;

use LWP::UserAgent;
require LWP::Authen::OAuth;

my $params =
[
#'oauth_consumer_key' => '3f7661c5e85d4e61821d5d4503753bd4',
#'oauth_consumer_secret' => 'cbb04dd0b755489f9378e8be12217e41',
'oauth_token_secret' => '0d921e3f2a4cfa179c078705d9cd96e8',
'oauth_verifier' => '2ii9khp1q733388r1bqv7n6q0t',
];

my $ua = LWP::Authen::OAuth->new(
  'oauth_consumer_key' => '3f7661c5e85d4e61821d5d4503753bd4',
  'oauth_consumer_secret' => 'cbb04dd0b755489f9378e8be12217e41',
);
$ua->cookie_jar(
            {
                'file' => "$ENV{HOME}/.cookies.txt"
             }
);
$ua->timeout(10);
$ua->env_proxy;

# Allow posts to redirect.
push @{ $ua->requests_redirectable }, 'POST';

my $request = $ua->post( 'https://api.fitbit.com/oauth/access_token',
  $params
);
die $request->as_string if $request->is_error;

# update the token secret from the HTTP response
$ua->oauth_update_from_response( $request );
