#!/usr/bin/env perl
use strict;
use warnings;

use LWP::Simple;
use JSON::Any;
use Data::Dumper;

#my $file = shift(@ARGV);
#die("File not found: $file") unless(-f $file);

#open(FILE, $file) or die("Cannot open file $file for read: $!");

my $json_string = get('http://api.bitcoincharts.com/v1/markets.json');

#my $json_string;
#while(<FILE>){
#  $json_string .= $_;  
#}

my $j = JSON::Any->new();

my $json_obj = $j->jsonToObj($json_string);
#print Dumper($json_obj);

#foreach my $market_hashref(@$json_obj){
foreach my $market_hashref(sort{$a->{'symbol'} cmp $b->{'symbol'}} @$json_obj){
#  if($market_hashref->{'currency'} eq 'USD'){
#    print Dumper($market_hashref);
#  }
  if($market_hashref->{'symbol'} eq 'mtgoxUSD'){
#    print Dumper($market_hashref);
  print "$market_hashref->{'latest_trade'},$market_hashref->{'ask'}\n";
  }

}
