#!/usr/bin/perl -w
#
#   IMPORTANT: READ THIS IN ITS ENTIRETY. YOU ARE THE FINAL AUTHORITY IN DETERMINING
#   WHAT HAPPENS ON YOUR COMPUTER. YOU SHOULD READ ALL DOCUMENTATION PERTAINING TO
#   THE INSTALLATION AND USE OF ALL SOFTWARE YOU INSTALL AND USE AND SHOULD MAKE 
#   REGULAR AND COMPLETE BACKUPS OF YOUR IMPORTANT DATA.
#
#   PF1 - Realtime Point & Figure Charting
#
#   -------------------------LEGAL INFO--------------------------------------------
#
#   This script is Copyright (C) 1999  Jim Michael and XMLWorks All Rights Reserved
#
#   This is version 1.0.0 (7 Jan 1999)
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
#   Download and parsing script for www.yahoo.com. This script will most
#   assuredly NOT work with other quote sources. Contact us for assistance
#   if you would like to use this script for other quote sources.
#
#   ------------------------------USAGE INFO-------------------------------------
#
#   USAGE: perl pf1
#
#   Note to Windows NT/95 users:
#
#   If you are on a Win32 platform (NT or Windows95/98) then we recommend that you
#   use Gurusamy Sarathy's Standard Win32 port of Perl 5.04 or higher. The ActiveState port
#   is newer, but this version is known to be stable and included all of the modules used
#   by QuoteMonster. You may download the free perl interpreter from
#   http://www.perl.com/ or see the XMLWorks website for location of the binary download.
#
#
#   ----------------------------------SUPPORT INFO--------------------------------------
#
#   Since this is free software, no support is offered. However, suggestions for improvements
#   to the program are always welcome. If you are using the program and find it useful,
#   please drop us a line sometime. We would enjoy hearing from you.
#
#   Snail Mail: XMLWorks
#               PO Box 941124
#               Atlanta, GA 31141-1124
#               USA 
#   Web: http://www.xmlworks.com/
#
#   Custom modifications to this script or other custom Internet programming
#   in Perl are also available.
#
#
# ----------------------- Enter your custom settings here ----------------------------- #
#
# Instructions:
#
# Lines with comments are preceded by the hash symbol (#). The following lines assign
# values to variables. Some values are numerical and some are not. The numerical values
# are not enclosed in single quotes, the non-numerical entries are enclosed in
# single quotes ('like this'). All perl statements must end with a semicolon (;) and a
# comment may follow on the same line by placing the hash symbol (#) before the comment. 

my $ticker        = '^OEX';              # ticker of the security being plotted
my $inputFile     = 'quote.txt';         # temporary storage file
my $outputFile    = 'oex.txt';           # contains parsed data in comma separated format
my $sleepTime     = 30;                  # time in seconds to wait between quote retrievals (3600 seconds per hour)
my $pfFile        = 'oex.html';          # file to store HTML
my $boxsize       = 10;                  # Each X or O represents this amount
my $multiplier    = 100;                 # price will be multiplied by this number
my $reversal      = 10;                  # price move which results in change of direction
my $output        = 1;                   # 1 for output to screen, 0 for output to HTML
my $cleanfile     = 0;                   # 1 to start with new file, 0 to append to old file.

# Enter proxy and port information
# ONLY if you must go through a proxy server:

my $proxy   = '';			 # proxy server
my $port    = '';			 # proxy server port
my $noproxy = '';			 # local domain

# Enter start and stop times here (hh:mm)

my $start='9:30';
my $stop='24:00';

# //////////////// DO NOT EDIT ANYTHING BELOW THIS LINE \\\\\\\\\\\\\\\\\\\\ #

use LWP::UserAgent;
use HTTP::Request;
use HTTP::Response;

# Wait until start time

($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
($startHours,$startMinutes)=split(/:/,$start);
($stopHours,$stopMinutes)=split(/:/,$stop);
$start=$startHours*60+$startMinutes;
$stop=$stopHours*60+$stopMinutes;
while (($hour * 60 + $min) < $start) {
        sleep 30;
        ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);
}
$product_id='Mozilla/3.0';
$ua = new LWP::UserAgent;
$ua->agent($product_id);
if ($proxy ne '' && $port ne '' && $noproxy ne '') {
	$ua->proxy('http', "http://$proxy:$port/"); 
	$ua->no_proxy("$noproxy"); 
}
my $data = '';
unlink $outputFile if ($cleanfile); 

# Do until stop time

while (($hour * 60 + $min) < $stop) {
	$URL = 'http://quote.yahoo.com/d/quotes.csv?s=';
	$URL .= $ticker."+";
	$URL .= '&f=sl1d1t1c1ohgv&e=.csv';
	$request = new HTTP::Request('GET', $URL);
   $response = new HTTP::Response;
   $response = $ua->request($request)->as_string;
   $data = $ua->request($request)->as_string;
	open (OUT, ">$inputFile");
	print OUT "$data";
	close OUT;
	open (IN,"$inputFile") || die("Can't open $inputFile - $!");
	(@quotes) = (<IN>);
   open (ALERT, ">>$outputFile") || die("Can't open alerts file for writing - $!");
	foreach $quote (@quotes) {
		if ($quote =~ /^"/) {
			($ticker,$last,$date,$time,$change,$low,$high,$vol) = split(/,/,$quote);
			#if ($last > 0) {$deltapercent = abs(100 * $change/$last);}
			$ticker =~ s/"//g;
			$ticker =~ tr/A-Z/a-z/;
			$date =~ s/"//g;
			$time =~ s/"//g;
			print ALERT "$ticker,$last,$date,$time,$change,$high,$low,$vol\n";
		}
	}
	close ALERT;
	unless (pf($outputFile,$pfFile,$boxsize,$reversal)) {
		print 'Possible problem with last update';
	}
        sleep $sleepTime;
        ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(time);

}
sub pf() {
	my ($i,$miny,$maxy,$y,$oldP,@g);
	my $in = shift;
	my $out = shift;
	my $boxsize = shift; 
	my $reversal = shift;
	my $direction = 0;
	$miny = 1000000;
	$maxy = 0;
	my $x = 1;
	my $boxes;
	my $newP;
	open (IN,$in) || die("Can't open input file $in - $!");
	while (<IN>) {
		chomp;
		($ticker,$last,$date,$time,$change,$low,$high,$vol) = split /,/;
		$last *= $multiplier;
		if ($direction == 1) {
			if ($last > $oldP) {
				$newP = $boxsize * int($last/$boxsize);
				for ($i = $oldP+$boxsize; $i < $newP+$boxsize; $i+=$boxsize) {
					$maxy = $i if ($i > $maxy);
					$g[$x][$i] = 'x';
				}
				$oldP = $newP;			
			}
			elsif ($last < $oldP) {
				$newP = $boxsize*int($last/$boxsize);
				if ($oldP - $newP > $reversal) {
					$x++;
					$direction = -1;
					for ($i = $oldP-$boxsize; $i > $newP-$boxsize; $i-=$boxsize) {
						$miny = $i if ($i < $miny);
						$g[$x][$i] = 'o';
					}
					$oldP = $newP;
				}
			}
		}
		elsif ($direction == -1) {
			if ($last < $oldP) {
				$newP = $boxsize * int($last/$boxsize);
				for ($i = $oldP-$boxsize; $i > $newP-$boxsize; $i-=$boxsize) {
					$miny = $i if ($i < $miny);
					$g[$x][$i] = 'o';
				}
				$oldP = $newP;
			}
			elsif ($last > $oldP) {
				$newP = $boxsize * int($last/$boxsize);
				if ($newP - $oldP > $reversal) {
					$x++;
					$direction = 1;
					for ($i = $oldP+$boxsize; $i < $newP+$boxsize; $i+=$boxsize) {
						$maxy = $i if ($i > $maxy);
						$g[$x][$i] = 'x';
					}
					$oldP = $newP;
				}
			}
		}
		else {
			if (defined($oldP)) {
				if ($last > $oldP) {
					$newP = $boxsize * int($last/$boxsize);
					if ($newP > $oldP) {
						$direction = 1;
						for ($i = $oldP; $i < $newP+$boxsize; $i+=$boxsize) {
							$maxy = $i if ($i > $maxy);
							$g[$x][$i] = 'x';
						}
					}
				}
				elsif ($last < $oldP) {
					$newP = $boxsize * int($last/$boxsize);
					if ($newP < $oldP) {
						$direction = -1;
						for ($i = $oldP; $i > $newP+$boxsize; $i+=$boxsize) {
							$miny = $i if ($i < $miny);
							$g[$x][$i] = 'o';
						}
					}
				}
			}
			else {
				$oldP = $boxsize*int($last/$boxsize);
			}
		}
	}
	close IN;
	my $maxx = $x;
	open (OUT,">$out") || die("Can't open output file $out - $!");
	print OUT '<html><head><META HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE"><META HTTP-EQUIV="REFRESH" CONTENT="30"></head><body><pre>';
	my $count = 0;
	my $g = '';
	if ($output) {
		system ('cls');
	}
	for ($y = $maxy; $y > $miny-$boxsize; $y-=$boxsize) {
		print OUT "$y ";
		if ($output) {
			print "$y ";
		}
		for ($x = 1; $x < $maxx + 1; $x++) {
			$g[$x][$y] = ' ' unless (defined($g[$x][$y]));
			$g .= $g[$x][$y];
		}
		$g =~ s/ *$//g;
		print OUT "$g\n"; #110
		if ($output) {
			print "$g\n";
		}
		$g = '';
	}
	close OUT;
	return 1;
}
